### ISSUE TITLE
Add cloudName key into the secret

### ISSUE THREAD

**Issue by michal-gubricky** [SovereignCloudStack/openstack-csp-helper#2]
The current situation is that when the user uses the `openstack csp helper` chart to create a secret, the user is not able to use a different cloud name other than the default. I suggest to add `cloudName` to the [secret](https://github.com/SovereignCloudStack/openstack-csp-helper/blob/main/templates/cloud-secret.yaml) something like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud_name" . }} 
data:
  cloudName: {{ include "cloud_name" . | b64enc }} 
  clouds.yaml: {{ toYaml .Values | b64enc }}
type: Opaque
```
